// Run only against the disposable fixture. Real settings/data and other origins are out of scope.
import assert from 'node:assert/strict'
import { mkdirSync, readFileSync } from 'node:fs'
import { chromium } from 'playwright'
const base = 'http://127.0.0.1:8772'
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
const page = await context.newPage(), errors = [], writes = []
page.on('pageerror', e => errors.push(e.message))
page.on('request', req => { if (/\/charter\/workspace\//.test(req.url()) && req.method() !== 'GET') writes.push({ method: req.method(), url: req.url(), body: req.postDataJSON() }) })
await context.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort())
const dir = '../../data/diagnostics/charter-markdown'
mkdirSync(dir, { recursive: true })
const api = async (path, data, method = 'POST') => {
  const res = await context.request.fetch(base + '/api/mindos' + path, { method, ...(data === undefined ? {} : { data }) })
  assert.equal(res.ok(), true, await res.text()); return res.json()
}
const history = () => api('/growth/charter', undefined, 'GET')
const editor = page.getByTestId('charter-workspace')
const input = () => editor.getByRole('textbox', { name: '章程正文（Markdown）', exact: true })
try {
  assert.equal((await (await context.request.get(base + '/api/health')).json()).version, 'task-routing-fixture')
  assert.equal((await history()).currentCharter, null, 'use a fresh disposable fixture')
  await page.goto(base + '/mindos/me/charter', { waitUntil: 'networkidle' })
  assert.equal((await history()).workspace, null, 'read-only page must not create a draft')
  assert.equal(writes.length, 0)
  await page.getByRole('button', { name: '通过对话生成', exact: true }).waitFor()
  await page.getByRole('button', { name: '编辑正文', exact: true }).click()
  await input().waitFor()
  assert.equal(await editor.locator('textarea').count(), 1)
  assert.equal(await editor.locator('input, select').count(), 0)
  const original = '\n# 我自己的章程\n\n## 诚实\n\n我重视诚实沟通。\n\n- 保留 **强调**、标点和空行。\n\n'
  await input().fill(original)
  await editor.getByRole('button', { name: '预览', exact: true }).click()
  await editor.getByRole('heading', { name: '我自己的章程', exact: true }).waitFor()
  await editor.getByRole('button', { name: '编辑正文', exact: true }).click()
  assert.equal(await input().inputValue(), original)
  await editor.getByRole('button', { name: '保存草稿', exact: true }).click()
  await editor.getByText(/草稿已保存.*尚未生效/).waitFor()
  let value = await history()
  assert.equal(value.currentCharter, null); assert.equal(value.workspace.document, original)
  const cid = value.workspace.conversationId
  assert.ok(writes.filter(w => w.method === 'PUT').every(w => w.body.document === original && !('clauses' in w.body) && !('sourceText' in w.body)))
  const downloaded = page.waitForEvent('download')
  await editor.getByRole('button', { name: '下载 .md', exact: true }).click()
  const download = await downloaded
  assert.equal(download.suggestedFilename(), '人生章程.md')
  assert.equal(readFileSync(await download.path(), 'utf8'), original)
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByRole('button', { name: '编辑正文', exact: true }).click()
  assert.equal(await input().inputValue(), original)
  await page.route('**/charter/workspace/*/publish', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: '合成发布失败，请重试。' }) }))
  await editor.getByRole('button', { name: '确认并生效', exact: true }).click()
  await editor.getByRole('alert').waitFor()
  assert.equal(await input().inputValue(), original)
  assert.equal((await history()).currentCharter, null)
  await page.unroute('**/charter/workspace/*/publish')
  await page.screenshot({ path: dir + '/editor-desktop.png', fullPage: true })
  await editor.getByRole('button', { name: '确认并生效', exact: true }).click()
  await page.getByText('只有你主动修改并确认，正式章程才会更新。', { exact: true }).waitFor()
  value = await history()
  assert.equal(value.currentCharter.document, original); assert.equal(value.currentCharter.version, 1); assert.equal(value.workspace, null)
  assert.ok(writes.filter(w => w.url.endsWith('/publish')).every(w => w.body.publishDocument === true && !('selectedClauseIds' in w.body)))
  await page.goto(base + '/mindos/c/' + cid + '?charter=1', { waitUntil: 'networkidle' })
  assert.equal((await history()).workspace, null); assert.equal(await page.locator('dialog[open]').count(), 0)
  const composer = page.locator('.zj-page__composer textarea')
  await composer.fill('未发送的对话不要被编辑器覆盖。')
  await page.getByRole('button', { name: /^查看章程草稿/ }).click()
  const drawer = page.getByRole('dialog', { name: '人生章程', exact: true })
  await drawer.getByRole('button', { name: '主动开始修改章程', exact: true }).click()
  await input().waitFor(); assert.equal(await input().inputValue(), original)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: dir + '/editor-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true)
  const box = await drawer.boundingBox(); assert.ok(box.x >= 0 && box.width <= 390)
  await page.keyboard.press('Escape')
  assert.equal(await composer.inputValue(), '未发送的对话不要被编辑器覆盖。')
  await page.goto(base + '/mindos/me/charter?version=1', { waitUntil: 'networkidle' })
  await page.getByText('正在查看历史版本，只读，不影响当前章程。', { exact: false }).waitFor()
  assert.equal(await page.getByRole('button', { name: '编辑正文', exact: true }).count(), 0)
  assert.deepEqual(errors, [])
  console.log('charter Markdown E2E: explicit start, single editor, exact preview/download, separate draft/publish, failure retention, immutable history and narrow drawer passed')
} catch (e) { await page.screenshot({ path: dir + '/failure.png', fullPage: true }); throw e }
finally { await browser.close() }
