import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { charterDocument, charterExecutionLabel, keepCharterEdits, newCharterClause, workspaceMarkdown, renderCharterClauses } from '../src/shared/charterWorkspace.ts'
const read = file => readFile(new URL('../src/' + file, import.meta.url), 'utf8')
const [page, chat, editor, routing, conversation, consent, document] = await Promise.all([
  'pages/CharterPage.vue', 'components/conversation/CharterConversation.vue', 'components/conversation/CharterWorkspaceEditor.vue',
  'services/taskRouting.ts', 'pages/ConversationPage.vue', 'components/conversation/RoutingConsent.vue', 'components/conversation/CharterDocument.vue',
].map(read))
const clause = newCharterClause()
assert.equal(clause.origin, 'manual')
assert.equal(clause.control, null)
assert.match(charterExecutionLabel(clause), /指导建议/)
assert.match(charterExecutionLabel({ ...clause, kind: 'aspiration' }), /不自动执行/)
assert.match(charterExecutionLabel({ ...clause, control: 'local_only' }), /仅本地处理/)
assert.match(charterExecutionLabel({ ...clause, scope: 'contextual' }), /需澄清/)
assert.equal(charterDocument({ document: '## 自由章节\n我自己写的内容', vision: '旧愿景' }), '## 自由章节\n我自己写的内容')
assert.match(charterDocument({ vision: '希望更从容', principles: ['诚实'] }), /我的愿望[\s\S]*希望更从容[\s\S]*我的原则/)
const baseline = { ...clause, text: '旧内容', section: '原章节' }
const merged = keepCharterEdits([baseline], [{ ...baseline, section: '别人改了章节' }, { ...clause, id: 'remote-new', text: '新增' }], [{ ...baseline, text: '我正在改的内容' }])
assert.equal(merged[0].text, '我正在改的内容')
assert.equal(merged[0].section, '别人改了章节')
assert.equal(merged[1].id, 'remote-new')
assert.deepEqual(keepCharterEdits([baseline], [baseline, { ...clause, id: 'remote-new' }], []).map(c => c.id), ['remote-new'])
assert.match(page, /workspace\/start/)
assert.match(page, /CharterWorkspaceEditor/)
assert.doesNotMatch(page, /saveGrowthCharter|charter-vision|charter-goals/)
assert.match(page, /PERSONAL CHARTER · 私人法典/)
assert.match(page, /工作稿 · 基于第/)
assert.match(page, /appearance="codex"/)
assert.match(editor, /'compact' \| 'codex'/)
assert.match(document, /charter-document--codex/)
assert.match(document, /markdown\.disable\('image'\)/)
assert.match(chat, /const open = ref\(false\)/)
assert.match(chat, /workspace\.value\?\.status !== 'active'/)
assert.doesNotMatch(chat.slice(chat.indexOf('async function refresh'), chat.indexOf('function schedule')), /workspace\/start/)
assert.match(chat, /分别核对，不会因发布章程而自动确认或提高贴合度/)
assert.equal((editor.match(/<textarea\b/g) ?? []).length, 1, 'one document, not a multi-field form')
assert.doesNotMatch(editor, /<input\b|<select\b|selectedClauseIds/)
assert.match(editor, /publishDocument: true/)
assert.match(editor, /document: markdown\.value/)
assert.match(editor, /章程正文（Markdown）/)
for (const label of ['编辑正文', '预览', '保存草稿', '确认并生效', '根据对话整理', '下载 .md', '采用这份正文']) assert.ok(editor.includes(label))
assert.match(editor, /if \(!dirty\.value\) apply\(result.workspace\)/)
assert.match(editor, /if \(outdated\.value\) throw new Error/)
assert.match(editor, /revision: base\.value\.revision/)
assert.match(editor, /保留我的正文/)
assert.match(editor, /if \(dirty\.value\) throw new Error\('保存期间/)
assert.match(editor, /旧稿中的原始想法/)
assert.match(editor, /加入正文/)
assert.match(page, /mode === 'chat' && editorDirty\.value/)
assert.match(editor, /saveBuffer\(\)[\s\S]*\/publish/)
assert.match(editor, /仅本地整理/)
const exact = '\n# 一篇章程\n\n- **粗体**\n\n'
assert.equal(workspaceMarkdown({ document: exact, documentFormat: 'markdown', sourceText: '不能静默合进正文的原始想法', clauses: [] }), exact)
assert.equal(workspaceMarkdown({ document: '', documentFormat: 'markdown', sourceText: '旧字段不能让已清空正文复活', clauses: [baseline] }), '')
assert.equal(workspaceMarkdown({ document: exact, sourceText: '旧文字', clauses: [] }), exact)
assert.equal(workspaceMarkdown({ document: '', sourceText: '仅原始文字\n不应丢失', clauses: [] }), '仅原始文字\n不应丢失')
const legacy = { ...baseline, text: '保留换行\n和标点。', scope: 'contextual', context: '工作场景' }
assert.match(renderCharterClauses([legacy]), /保留换行\n和标点。.*工作场景/s)
assert.equal(workspaceMarkdown({ document: '', sourceText: '不要静默拼接', clauses: [legacy] }), renderCharterClauses([legacy]))
assert.match(routing, /requestId: body\.requestId \|\| crypto\.randomUUID\(\)/)
assert.doesNotMatch(conversation, /sendBody\.requestId = crypto\.randomUUID/)
assert.match(routing, /charter-exception/)
assert.match(routing, /charterExceptionId: result\.exceptionId.*continue/s)
assert.match(consent, /也不代表同意发送资料/)
assert.match(consent, /仅本轮例外，继续核对资料权限/)
console.log('charter workspace: one Markdown document, exact legacy fallback, explicit sessions, separate confirmation and stable permission contracts passed')
