// Built UI + disposable real APIs; no real account, box, or model provider.
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { chromium } from 'playwright'
import { expect } from 'playwright/test'

const base = 'http://127.0.0.1:8778'
assert.equal((await (await fetch(base + '/api/health')).json()).version, 'chat-simplification-fixture')
const info = async () => (await (await fetch(base + '/__fixture')).json())
const initial = await info()
assert.equal(initial.synthetic, true)
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = [], writes = []
page.on('pageerror', error => errors.push(error.message))
page.on('request', req => { if (['POST', 'PUT', 'DELETE'].includes(req.method())) writes.push({ url: req.url(), body: req.postDataJSON() }) })
await page.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort())
const input = page.getByRole('textbox', { name: '输入消息', exact: true })
const screenshotDir = '/private/tmp/zhijun-chat-simple-screenshots'
await mkdir(screenshotDir, { recursive: true })
async function enter(id) { await page.goto(base + '/mindos/c/' + id); await expect(input).toBeVisible() }
async function send(text) { await input.fill(text); await page.getByRole('button', { name: '发送', exact: true }).click() }
async function stopped() { await expect(page.getByRole('button', { name: '停止', exact: true })).toHaveCount(0) }
async function cleanControls() {
  await expect(page.getByTestId('routing-local-mode')).toHaveCount(0)
  await expect(page.getByTestId('routing-online-mode')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /模型与授权|改用本地/ })).toHaveCount(0)
}
async function saved(id) { return (await (await fetch(base + '/api/mindos/conversations/' + id)).json()).messages }
try {
  await enter(initial.cases.legacy)
  const brand = page.locator('.ws-sidebar__brand')
  await expect(brand.locator('.ws-sidebar__seal')).toHaveText('知')
  await expect(brand.locator('.ws-sidebar__brand-text')).toHaveText('知君')
  await expect(brand).not.toContainText('半人马')
  const aboutButton = brand.getByRole('button', { name: '关于知君', exact: true })
  const about = page.getByRole('dialog', { name: '关于知君', exact: true })
  await aboutButton.click()
  await expect(about).toContainText('半人马人工智能出品')
  await expect(about.getByRole('img', { name: '半人马人工智能', exact: true })).toBeVisible()
  await expect(about).not.toContainText('AI')
  await page.screenshot({ path: screenshotDir + '/05-about-zhijun-desktop.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(about).not.toBeVisible()
  await expect(aboutButton).toBeFocused()
  await page.screenshot({ path: screenshotDir + '/03-original-brand-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 900, height: 900 })
  await expect(brand.locator('.ws-sidebar__brand-text')).not.toBeVisible()
  await expect(brand.locator('.ws-sidebar__seal')).toBeVisible()
  await aboutButton.click()
  await expect(about).toBeVisible()
  await about.getByRole('button', { name: '关闭关于知君', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await cleanControls()
  const before = await info(), legacyCount = (await saved(initial.cases.legacy)).length
  await send('合成草稿：继续之前先确认资料。')
  const setup = page.getByRole('dialog', { name: '继续前，确认资料使用', exact: true })
  await expect(setup).toBeVisible()
  await expect(setup).toContainText('受保护的旧历史不会自动')
  await expect(setup).not.toContainText(/openai|synthetic|本地模型|在线模型/i)
  await setup.getByRole('button', { name: '取消，保留输入' }).click()
  await expect(input).toHaveValue('合成草稿：继续之前先确认资料。')
  assert.equal((await saved(initial.cases.legacy)).length, legacyCount)
  assert.equal((await info()).onlineRequests, before.onlineRequests)
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await setup.getByRole('checkbox').check()
  await setup.getByRole('button', { name: '确认并继续' }).click()
  await expect(page.getByText('合成回答：先核对这次的目标，保留可以调整的空间。', { exact: true })).toBeVisible()
  await stopped()
  assert.ok(!JSON.stringify((await info()).payloads).includes('PROTECTED_OLD_HISTORY'))
  await page.getByRole('button', { name: '回答依据', exact: true }).last().click()
  await expect(page.locator('.zj-prov').last()).not.toContainText(/openai|synthetic|在线处理|本地处理|提示约/i)
  await page.reload()
  await expect(page.getByText('合成回答：先核对这次的目标，保留可以调整的空间。', { exact: true })).toBeVisible()

  // Recovery stays reachable without opening model settings.
  await enter(initial.cases.short)
  await page.getByRole('button', { name: /整理未完成/ }).click()
  const tasks = page.getByRole('dialog', { name: '整理状态', exact: true })
  await expect(tasks).not.toContainText(/模型|openai|synthetic/i)
  await tasks.getByRole('button', { name: '重新整理', exact: true }).click()
  await expect.poll(() => writes.filter(w => w.url.endsWith('/routing/resume')).length).toBe(1)
  assert.equal(writes.find(w => w.url.endsWith('/routing/resume')).body.localOnly, false)
  await expect(tasks).toContainText(/正在重新准备|没有需要处理/)
  await tasks.getByRole('button', { name: '关闭整理状态' }).click()

  await fetch(base + '/__fixture/fail', { method: 'POST' })
  await send('合成测试：这次回答暂时失败。')
  await expect(page.getByText('暂时无法回答，请重试。原消息已保留。')).toBeVisible()
  await stopped()
  await cleanControls()
  const failedCount = (await saved(initial.cases.short)).length
  await fetch(base + '/__fixture/recover', { method: 'POST' })
  await page.locator('.zj-turn').last().getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.locator('.zj-turn').last()).toContainText('合成回答：先核对这次的目标')
  await stopped()
  assert.equal((await saved(initial.cases.short)).length, failedCount, 'retry updates the saved pair without duplicating the question')

  // Missing-source authorization still requires an explicit choice.
  await fetch(base + '/__fixture/source-consent', { method: 'POST' })
  await enter(initial.cases.consent)
  const consentBefore = (await saved(initial.cases.consent)).length
  await send('星桥项目为什么迟迟不想推进？')
  const consent = page.getByRole('dialog', { name: '本次资料使用确认', exact: true })
  await expect(consent).toBeVisible()
  await expect(consent).not.toContainText(/openai|synthetic|模型|系统提示/i)
  await consent.getByRole('button', { name: '取消，保留输入' }).click()
  await expect(input).toHaveValue('星桥项目为什么迟迟不想推进？')
  assert.equal((await saved(initial.cases.consent)).length, consentBefore)
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await consent.getByRole('button', { name: '确认使用所选资料' }).click()
  await expect(page.getByText('合成回答：先核对这次的目标，保留可以调整的空间。', { exact: true })).toBeVisible()
  await stopped()
  await cleanControls()
  await page.screenshot({ path: screenshotDir + '/01-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.ws-sidebar')).toHaveAttribute('aria-hidden', 'true')
  await expect.poll(() => page.locator('.ws-sidebar').evaluate(el => el.getBoundingClientRect().right <= 0)).toBe(true)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: screenshotDir + '/02-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '打开导航菜单' }).click()
  await expect(brand.locator('.ws-sidebar__brand-text')).toBeVisible()
  await expect(brand).not.toContainText('半人马')
  await expect.poll(() => page.locator('.ws-sidebar').evaluate(el => Math.abs(el.getBoundingClientRect().left) < 1)).toBe(true)
  await page.screenshot({ path: screenshotDir + '/04-original-brand-mobile.png', fullPage: true })
  await aboutButton.click()
  await expect(about).toBeVisible()
  await expect.poll(() => about.evaluate(el => el.getBoundingClientRect().width <= innerWidth)).toBe(true)
  await expect(about).toContainText('人工智能拓展人的能力')
  await page.screenshot({ path: screenshotDir + '/06-about-zhijun-mobile.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(aboutButton).toBeFocused()
  await page.getByRole('button', { name: '关闭导航', exact: true }).click()

  // The same shared component retains the full settings presentation.
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(base + '/mindos/settings')
  await expect(page.getByTestId('routing-local-mode')).toBeVisible()
  await expect(page.getByTestId('routing-online-mode')).toBeVisible()
  await expect(page.getByRole('button', { name: /模型与授权/ })).toBeVisible()
  const final = await info()
  assert.equal(final.localRequests, 0)
  assert.deepEqual(final.defaultMode, initial.defaultMode)
  assert.ok(writes.every(w => !/routing\/default$|default-consent|routing\/handling|system\/models/.test(w.url)))
  assert.deepEqual(errors, [])
  console.log('PASS conversation-only UI: opt-in/cancel, protected history, existing source grants, retry persistence, pending recovery, provenance, mobile, unchanged settings/defaults, zero local replies')
} finally { await browser.close() }
