import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { conversationActions, conversationListQuery, conversationTitleError, retainNewerConversationMetadata } from '../src/shared/conversationManagement.ts'
import { createSessionGate } from '../src/composables/sessionGate.ts'

assert.equal(conversationTitleError('  新名称  '), '')
assert.equal(conversationTitleError('   '), '请输入对话名称。')
assert.equal(conversationTitleError('知'.repeat(80)), '')
assert.equal(conversationTitleError('知'.repeat(81)), '对话名称最多 80 个字。')
assert.equal(conversationTitleError('🙂'.repeat(80)), '', 'character count matches the backend instead of counting UTF-16 halves')
assert.equal(conversationActions({ status: 'active', pinnedAt: null }).find(a => a.action === 'pin').label, '置顶')
assert.equal(conversationActions({ status: 'archived', pinnedAt: 'now' }).find(a => a.action === 'pin').label, '取消置顶')
assert.equal(conversationActions({ status: 'archived' }).find(a => a.action === 'restore').label, '移回最近')
assert.equal(conversationActions({ status: 'active' }, false).some(a => a.action === 'delete'), false)
assert.deepEqual(conversationListQuery('archived', ' 海湾 ', 'all'), { status: 'all', q: '海湾', offset: 0, limit: 30 })
assert.deepEqual(conversationListQuery('archived', '', 'all'), { status: 'archived', offset: 0, limit: 30 }, 'clearing search restores previous tab')
assert.deepEqual(conversationListQuery('active', '海湾', 'archived', 30), { status: 'archived', q: '海湾', offset: 30, limit: 30 })
const gate = createSessionGate()
const old = gate.next()
gate.invalidate()
const latest = gate.next()
assert.equal(gate.isCurrent(old), false)
assert.equal(gate.isCurrent(latest), true)
const newest = { id: 'a', metadataRevision: 2, title: '新名称', status: 'archived', pinnedAt: 'new-pin', messageCount: 3 }
const delayed = { id: 'a', metadataRevision: 1, title: '旧名称', status: 'active', pinnedAt: null, messageCount: 4 }
assert.deepEqual(retainNewerConversationMetadata(delayed, newest), { ...newest, messageCount: 4 }, 'retain newer metadata without discarding fresh message data')
assert.equal(retainNewerConversationMetadata(newest, delayed), newest)

const read = path => readFile(new URL(path, import.meta.url), 'utf8')
const [page, list, rename, api] = await Promise.all([
  read('../src/pages/ConversationPage.vue'), read('../src/components/conversation/ConversationList.vue'),
  read('../src/components/conversation/RenameConversationDialog.vue'), read('../src/services/api.ts'),
])
assert.match(page, /conversationListAbort\?\.abort\(\)/)
assert.match(page, /conversationListGate\.isCurrent\(ticket\)/)
assert.match(page, /setTimeout\(\(\) => void loadConversations\(\), 250\)/)
assert.match(page, /expectedRevision: undo\.conversation\.metadataRevision/)
assert.match(page, /conversationSearchScope\.value = 'all'/)
assert.match(page, /res\.total/)
assert.match(page, /res\.hasMore/)
assert.match(page, /current\.value = rememberConversationMetadata\(detail\.conversation\)/)
assert.match(page, /messageId\) void revealMessage\(messageId\)/)
assert.match(page, /typeof route\.query\.message === 'string'\) return/)
const metadataRefresh = page.slice(page.indexOf('async function refreshCurrentMetadata('), page.indexOf('async function manageConversation('))
assert.doesNotMatch(metadataRefresh, /messages\.value|composerRef|streaming\.value\s*=/)
const management = page.slice(page.indexOf('async function manageConversation('), page.indexOf('function toUi('))
assert.doesNotMatch(management, /composerRef|messages\.value|router\.(push|replace)/, 'management must not navigate or clear drafts')
assert.match(list, /c\.searchMatch\.snippet/)
assert.doesNotMatch(list, /v-html|opacity:\s*0/)
assert.match(list, /aria-label="搜索对话标题和正文"/)
assert.match(list, /c\.status === 'archived'/)
assert.match(list, /c\.pinnedAt/)
assert.match(list, /conversationActions\(c, allowRemove\)/)
assert.match(page, /conversationActions\(current, !guidedOnboarding\)/)
assert.doesNotMatch(list, /<MoreMenu v-if="allowRemove"/)
assert.match(rename, /@submit\.prevent="save"/)
assert.match(rename, /@cancel\.prevent="close"/)
assert.match(rename, /watch\(\(\) => props\.conversation\?\.id/)
assert.match(rename, /returnFocus\.focus\(\{ preventScroll: true \}\)/)
assert.match(api, /options: number \| ConversationListOptions = 50, signal\?: AbortSignal/)
assert.match(api, /method: 'PATCH'/)
const composer = await read('../src/components/conversation/Composer.vue')
assert.match(composer, /previous \|\| LANDING_DRAFT/)
assert.match(composer, /storedDraft\(next \|\| LANDING_DRAFT\)/)
console.log('conversation management: title boundaries, scope restoration, pagination, stale request guards, metadata-only writes and plain-text snippets passed')
