// Real Vue + existing HTTP routes + temporary SQLite; no real account or model.
import assert from 'node:assert/strict'
import { mkdir, readFile } from 'node:fs/promises'
import { chromium } from 'playwright'
import { expect } from 'playwright/test'
const origin = process.env.REVISIT_ORIGIN || 'http://127.0.0.1:8777'
assert.equal((await (await fetch(origin + '/api/health')).json()).version, 'zhijun-revisit-fixture')
const fixture = await (await fetch(origin + '/__fixture')).json()
assert.equal(fixture.synthetic, true)
const catalog = JSON.parse(await readFile(new URL('../../shared/product-operations.json', import.meta.url), 'utf8'))
const known = catalog.operations.map(op => ({ method: op.method, path: new RegExp('^' + op.path.replace(/\{[^}]+\}/g, '[^/]+') + '$') }))
const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' })
const errors = [], requests = [], screenshots = '/private/tmp/zhijun-review-screenshots'
await mkdir(screenshots, { recursive: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
try {
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', req => { if (new URL(req.url()).pathname.startsWith('/api/')) requests.push({ method: req.method(), path: new URL(req.url()).pathname }) })
  const open = () => page.goto(origin + '/mindos/review')
  const card = page.getByTestId(`revisit-${fixture.decisionId}`)
  const pick = id => page.getByTestId(`revisit-pick-${id}`)
  const group = page.getByRole('group', { name: '回看分类' })
  await open()
  await expect(page.getByRole('main').getByRole('heading', { name: '回看', exact: true })).toBeVisible()
  await expect(page.locator('.experience-card')).toHaveCount(2)
  for (const id of [fixture.futureId, fixture.conversationId, fixture.sourceId]) await expect(pick(id)).toHaveCount(0)
  const nav = page.getByRole('navigation', { name: '主导航' })
  await expect(nav.getByRole('link')).toHaveCount(5)
  await expect(nav.getByRole('link', { name: '回看', exact: true })).toHaveAttribute('aria-current', 'page')
  // Cancel does not write; selecting a chat beyond the first page survives reload.
  await page.getByRole('button', { name: '选一段经历', exact: true }).click()
  await page.getByRole('region', { name: '选择值得回看的经历' }).getByRole('button', { name: '取消', exact: true }).click()
  assert.equal(requests.filter(r => r.method !== 'GET').length, 0)
  await page.getByRole('button', { name: '选一段经历', exact: true }).click()
  await page.getByRole('button', { name: '加载更早的经历' }).click()
  await page.getByRole('button', { name: '选入：合成：一次普通的团队交流', exact: true }).click()
  const ordinary = page.getByTestId(`revisit-${fixture.conversationId}`)
  await expect(ordinary).toContainText('昨天和团队把分工聊清楚了')
  await expect(page.locator('.experience-card')).toHaveCount(3)
  await page.reload()
  await expect(pick(fixture.conversationId)).toBeVisible()
  await pick(fixture.conversationId).click()
  await expect(ordinary).toContainText('昨天和团队把分工聊清楚了')
  await ordinary.getByText('看看当时的原话', { exact: true }).click()
  await page.screenshot({ path: screenshots + '/01-review-desktop.png', fullPage: true })
  // Defer/restore is durable and never deletes history.
  await ordinary.getByRole('button', { name: '暂时不回看', exact: true }).click()
  await expect(pick(fixture.conversationId)).toHaveCount(0)
  await page.reload()
  await expect(pick(fixture.conversationId)).toHaveCount(0)
  await group.getByRole('button', { name: /^暂放/ }).click()
  await expect(ordinary).toBeVisible()
  await ordinary.getByRole('button', { name: '放回回看', exact: true }).click()
  await expect(ordinary).toBeVisible()
  assert.equal(requests.filter(r => r.method !== 'GET').length, 0)
  // Failed source reads are explicit, with no stale quote, and recover through retry.
  let failDetail = true
  await page.route(`**/api/mindos/conversations/${fixture.conversationId}`, route => failDetail ? route.fulfill({ status: 503, json: { detail: '合成读取失败' } }) : route.continue())
  await pick(fixture.decisionId).click()
  await pick(fixture.conversationId).click()
  await expect(ordinary).toContainText('这段经历的原话暂时没有打开')
  await expect(ordinary).not.toContainText('昨天和团队把分工聊清楚了')
  failDetail = false
  await ordinary.getByRole('button', { name: /重试/ }).click()
  await expect(ordinary).toContainText('昨天和团队把分工聊清楚了')
  // Deep links also open a future choice outside the default queue.
  await page.goto(`${origin}/mindos/reflections?decisionId=${fixture.futureId}&action=outcome`)
  await expect(page.locator(`#outcome-result-${fixture.futureId}`)).toBeVisible()
  assert.ok(page.url().includes('/review?'))
  await page.getByTestId(`revisit-${fixture.futureId}`).getByRole('button', { name: '取消', exact: true }).click()
  await page.goto(`${origin}/mindos/reflections?decisionId=${fixture.decisionId}&action=outcome`)
  await card.locator(`#outcome-result-${fixture.decisionId}`).fill('合成结果：两周内完成了一次交付。')
  await card.getByRole('button', { name: '保存结果', exact: true }).click()
  await expect(card).toContainText('合成结果：两周内完成了一次交付。')
  await page.goto(origin + '/mindos/judgments')
  await pick(fixture.decisionId).click()
  await expect(card).toContainText('合成结果：两周内完成了一次交付。')
  await card.getByRole('button', { name: '留下经验', exact: true }).click()
  await card.locator(`#review-reflection-${fixture.decisionId}`).fill('合成复盘：提前讲清楚范围对这次合作有帮助。')
  await card.locator(`#review-lessons-${fixture.decisionId}`).fill('这只适用于这次试点，仍需更多经历。')
  await card.locator(`#review-next-${fixture.decisionId}`).fill('与对方核对下一次合作的范围。')
  await card.getByRole('button', { name: '确认完成复盘', exact: true }).click()
  await expect(card).toContainText('合成复盘：提前讲清楚范围对这次合作有帮助。')
  await page.reload()
  await group.getByRole('button', { name: /^留下的经验/ }).click()
  await expect(card).toContainText('这只适用于这次试点，仍需更多经历。')
  // Prefill never sends; reopen reuses the existing review conversation.
  await card.getByRole('button', { name: '和知君一起回看', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '输入消息', exact: true })).toHaveValue(/我想一起回看这段经历/)
  const reviewUrl = page.url().split('?')[0]
  assert.equal((await (await fetch(origin + '/__fixture')).json()).requests, fixture.requests)
  await open()
  await group.getByRole('button', { name: /^留下的经验/ }).click()
  await card.getByRole('button', { name: '和知君一起回看', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '输入消息', exact: true })).toHaveValue(/我想一起回看这段经历/)
  assert.equal(page.url().split('?')[0], reviewUrl)
  await open()
  await pick(fixture.conversationId).click()
  await ordinary.getByRole('link', { name: '和知君一起回看', exact: true }).click()
  const input = page.getByRole('textbox', { name: '输入消息', exact: true })
  await expect(input).toHaveValue(/我想一起回看这段经历/)
  assert.equal((await (await fetch(origin + '/__fixture')).json()).requests, fixture.requests)
  await input.fill('合成补充：这次交流只适用于新团队，熟悉的团队不需要同样的安排。')
  await page.getByRole('button', { name: '发送', exact: true }).click()
  const consent = page.getByRole('dialog', { name: '继续前，确认资料使用', exact: true })
  await expect(consent).toBeVisible()
  await consent.getByRole('button', { name: '取消，保留输入' }).click()
  await expect(input).toHaveValue('合成补充：这次交流只适用于新团队，熟悉的团队不需要同样的安排。')
  assert.equal((await (await fetch(origin + '/__fixture')).json()).requests, fixture.requests)
  await page.getByRole('button', { name: '发送', exact: true }).click()
  await consent.getByRole('checkbox').check()
  await consent.getByRole('button', { name: '确认并继续' }).click()
  await expect(page.getByText('合成回复：可以补充后来发生的事情。这次观察只适用于你说的情境，你可以继续修正。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('合成补充：这次交流只适用于新团队，熟悉的团队不需要同样的安排。', { exact: true })).toBeVisible()
  // Archive means read-only, even after explicit selection.
  await page.goto(origin + '/mindos/growth')
  await page.getByRole('button', { name: '选一段经历', exact: true }).click()
  await page.getByRole('button', { name: '加载更早的经历' }).click()
  await page.getByRole('button', { name: '选入：合成：已经归档的经历', exact: true }).click()
  const archived = page.getByTestId(`revisit-${fixture.archivedId}`)
  await expect(archived).toContainText('合成原话：那次经历已告一段落。')
  await expect(archived.getByRole('link', { name: '和知君一起回看', exact: true })).toHaveCount(0)
  await expect(archived.getByRole('link', { name: '查看原对话（已归档）', exact: true })).toBeVisible()
  // Storage failure must not claim success or hide a record.
  await page.evaluate(() => { window.__setItem = Storage.prototype.setItem; Storage.prototype.setItem = () => { throw new DOMException('full', 'QuotaExceededError') } })
  await archived.getByRole('button', { name: '暂时不回看', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: '回看安排没有保存成功' })).toBeVisible()
  await expect(pick(fixture.archivedId)).toBeVisible()
  await page.evaluate(() => { Storage.prototype.setItem = window.__setItem })
  for (const width of [800, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: `${screenshots}/02-review-${width}.png`, fullPage: true })
  }
  assert.deepEqual(errors, [])
  assert.equal(requests.filter(r => r.path.includes('/reflections')).length, 0)
  const nonCatalog = requests.filter(r => !['/api/health', '/api/mindos/access-context'].includes(r.path)
    && !known.some(op => op.method === r.method && op.path.test(r.path)))
  assert.deepEqual(nonCatalog, [], 'all business requests use existing operations')
  console.log('PASS selective revisit: inclusion, pagination, local persistence, cancel/defer/restore, source failure/retry, result/review persistence, dedup, deep links, reuse, explicit send, archive, storage failure, 800/390/320 layout, existing APIs')
} catch (error) {
  console.error('FAILED AT', page.url(), (await page.locator('main').innerText()).slice(-4000))
  await page.screenshot({ path: screenshots + '/failure.png', fullPage: true })
  throw error
} finally { await browser.close() }
