// P1 设置页回归：结构化错误、密钥清除和乐观锁冲突必须保持受控接线。
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const settings = await readFile(new URL('../src/pages/SettingsPage.vue', import.meta.url), 'utf8')
const api = await readFile(new URL('../src/services/api.ts', import.meta.url), 'utf8')

assert.match(api, /export class ApiError/)
assert.match(api, /throw new ApiError\(message, res\.status, code, details, preview, ragV2, similarRuleId, retryAfter, traceId\)/)
assert.match(api, /new Headers\(init\?\.headers\)/)
assert.match(api, /headers\.set\('X-Requested-By', 'centaur-vdb'\)/)
assert.match(settings, /ExternalProvidersPanel/)
assert.doesNotMatch(settings, /v-model="cApiKey"|v-model="cBaseUrl"|v-model="cModel"/)
assert.match(settings, /conflictPrompt\.value = true/)
assert.match(settings, /onConflictLoadLatest/)
assert.doesNotMatch(api, /ssrfProtectionEnabled|setSsrfProtection/)
assert.doesNotMatch(settings, /SSRF|ssrfProtectionEnabled/)
assert.doesNotMatch(settings, /qaDiagnostics/)
assert.match(settings, /async function disableExternalChatImmediately/)
assert.match(settings, /externalEnabled: false/)
assert.match(settings, /@click="disableExternalChatImmediately"/)
assert.match(settings, /await routingPanel\.value\?\.ensureLocal\(\)/)
const pauseFlow = settings.slice(settings.indexOf('async function disableExternalChatImmediately'), settings.indexOf('async function saveChat'))
assert.ok(pauseFlow.indexOf('ensureLocal()') < pauseFlow.indexOf('externalEnabled: false'), 'switch the default to local before disabling the online channel')
assert.ok(pauseFlow.lastIndexOf('ensureLocal()') > pauseFlow.indexOf('externalEnabled: false'), 'verify and repair the local postcondition after disabling the online channel')
assert.match(pauseFlow, /已打开的对话保留原选择/)
assert.match(settings, /新对话使用哪个模型/)
assert.match(settings, /新对话请选择上方“本地模型”，已打开的对话可在对话顶部切换/)
assert.match(settings, /routingPanel\.value\?\.refresh\(\)/)
assert.match(settings, /refreshRoutingReliably/)
assert.match(settings, /activateOnlineChannelFromRouting/)
assert.match(settings, /panel\.activateFromRouting\(\)/)
assert.match(settings, /:activate-online-channel="activateOnlineChannelFromRouting"/)
assert.match(settings, /:external-enabled="cExternal"/)
assert.match(settings, /@activated="handleProviderActivated"/)
assert.match(settings, /保存超时设置/)
assert.match(api, /configurationRequired\?: boolean/)
assert.match(settings, /cfg\.configurationRequired \? \(cfg\.configurationMessage/)
assert.match(settings, /v-if="cConfigurationMessage"[^>]+role="status"[^>]+data-testid="workspace-model-configuration-notice"/)
assert.match(api, /activateExternalProvider/)
assert.match(api, /getExternalProviderModels/)
assert.match(api, /material-runtime\/pull/)
assert.match(api, /nextCursor/)

console.log('settings-runtime: runtime/model routing contracts OK')
